name = "RandomBasedArrays"
uuid = "079b6ec6-a4f7-11e9-0358-1904ae85a441"
authors = ["Mosè Giordano"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
